services:
  spark-notebook:
    build: .
    ports:
      - "8888:8888"   # Jupyter Notebook
      - "4040:4040"   # Spark UI
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks
      - ./data:/home/jovyan/work/data
    environment:
      - JUPYTER_ENABLE_LAB=yes
